
import Image from "next/image";
const Technologies=()=>{
    return(
        <section id="projects" className="container mx-auto px-4 py-24">
                  <h2 className="text-3xl font-bold mb-12 text-center">Technologies</h2>
                  <div className="relative w-full overflow-hidden">
                    <div className="flex space-x-6 py-4 animate-scroll">
                      <div className="flex space-x-6 min-w-max">
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg"
                          width="130"
                          height="50"
                          alt="JavaScript"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg"
                          width="130"
                          height="50"
                          alt="TypeScript"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg"
                          width="130"
                          height="50"
                          alt="React"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg"
                          width="130"
                          height="50"
                          alt="Python"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/csharp/csharp-original.svg"
                          width="130"
                          height="50"
                          alt="C#"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-line-wordmark.svg"
                          width="130"
                          height="50"
                          alt="AWS"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/android/android-original.svg"
                          width="130"
                          height="50"
                          alt="Android"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg"
                          width="130"
                          height="50"
                          alt="Azure"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-original.svg"
                          width="130"
                          height="50"
                          alt="Bootstrap"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/docker/docker-original.svg"
                          width="130"
                          height="50"
                          alt="Docker"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg"
                          width="130"
                          height="50"
                          alt="GitLab"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/git/git-original.svg"
                          width="130"
                          height="50"
                          alt="Git"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/graphql/graphql-plain.svg"
                          width="130"
                          height="50"
                          alt="GraphQL"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/java/java-original.svg"
                          width="130"
                          height="50"
                          alt="Java"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jira/jira-original.svg"
                          width="130"
                          height="50"
                          alt="Jira"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/kubernetes/kubernetes-plain.svg"
                          width="130"
                          height="50"
                          alt="Kubernetes"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg"
                          width="130"
                          height="50"
                          alt="MongoDB"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mysql/mysql-original.svg"
                          width="130"
                          height="50"
                          alt="MySQL"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg"
                          width="130"
                          height="50"
                          alt="Next.js"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/npm/npm-original-wordmark.svg"
                          width="130"
                          height="50"
                          alt="npm"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/opencv/opencv-original.svg"
                          width="130"
                          height="50"
                          alt="OpenCV"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pandas/pandas-original.svg"
                          width="130"
                          height="50"
                          alt="Pandas"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/postgresql/postgresql-original.svg"
                          width="130"
                          height="50"
                          alt="PostgreSQL"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/pytorch/pytorch-original.svg"
                          width="130"
                          height="50"
                          alt="PyTorch"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redis/redis-original.svg"
                          width="130"
                          height="50"
                          alt="Redis"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg"
                          width="130"
                          height="50"
                          alt="Redux"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/spring/spring-original.svg"
                          width="130"
                          height="50"
                          alt="Spring"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sqlite/sqlite-original.svg"
                          width="130"
                          height="50"
                          alt="SQLite"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tensorflow/tensorflow-original.svg"
                          width="130"
                          height="50"
                          alt="TensorFlow"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original-wordmark.svg"
                          width="130"
                          height="50"
                          alt="TailwindCSS"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/trello/trello-plain.svg"
                          width="130"
                          height="50"
                          alt="Trello"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg"
                          width="130"
                          height="50"
                          alt="VSCode"
                        />
                        <Image
                          src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/xcode/xcode-original.svg"
                          width="130"
                          height="50"
                          alt="Xcode"
                        />
                      </div>
                    </div>
                  </div>
                </section>
    )
}

export default Technologies